export const AUTH_ERROR = {
  INVALID_PAYLOAD: "AUTH_INVALID_PAYLOAD",
  INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  GOOGLE_SIGN_IN_REQUIRED: "AUTH_GOOGLE_SIGN_IN_REQUIRED",
  USER_INVALID: "AUTH_USER_INVALID",
  EMAIL_ALREADY_REGISTERED: "AUTH_EMAIL_ALREADY_REGISTERED",
  CREATED_USER_NOT_FOUND: "AUTH_CREATED_USER_NOT_FOUND",
  CREATED_USER_INVALID_ID: "AUTH_CREATED_USER_INVALID_ID",
  VERIFICATION_MAIL_FAILED: "AUTH_VERIFICATION_MAIL_FAILED",
  INTERNAL_SERVER_ERROR: "AUTH_INTERNAL_SERVER_ERROR",
  EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
  PASSWORD_RESET_INVALID_TOKEN: "AUTH_PASSWORD_RESET_INVALID_TOKEN",
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR)[keyof typeof AUTH_ERROR];
